//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movy
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Actor { get; set; }
        public string Director { get; set; }
    }
}
